### ISSUE TITLE
Game sometimes rotates to portrait orientation after ad is played

### ISSUE THREAD

**Issue by justin-espedal** [polydes/unityads#4]
This has been an issue for some time. There's been a lot of requests for this to be fixed on Discord lately.

When an ad is closed, it sometimes forces the game into portrait orientation, even if the game doesn't support portrait orientation.

> (FMStudio) Of I can give my little contribution, it happens badly if orientation is locked (i.e. the only way to restore back to landscape is to force close the app) but it still happens if orientation is not locked. In this case though you can simply rotate your phone to restore. At least on my devices.

**Comment by justin-espedal** [comment]
1. This is what a Stencyl game typically looks like:

   ```
   <SDL_uikitwindow>
      | <UITransitionView>
      |    | <UIDropShadowView>
      |    |    | <SDL_uikitopenglview>
      |    |    |    | <UITextField; hidden = YES> (for Stencyl's soft keyboard)
   ```

2. When the unity ads initialization block is run, we end up with this:

   ```
   <SDL_uikitwindow>
      | <USRVWebViewBackgroundView; hidden = YES>
      |    | <WKWebView; hidden = YES>
      | <UITransitionView>
      |    | <UIDropShadowView>
      |    |    | <SDL_uikitopenglview>
      |    |    |    | <UITextField; hidden = YES>
   ```
   
   `USRVWebViewBackgroundView` is part of the Unity Ads iOS SDK
   
   Presumably it's part of the view hierarchy when no ads have been displayed because it has to do with loading content in and being able to show it as soon as it's requested.

3. When a video ad is displayed
   
      ```
   <SDL_uikitwindow>
      | <USRVWebViewBackgroundView; hidden = YES>
      | <UITransitionView>
      |    | <UIDropShadowView>
      |    |    | <SDL_uikitopenglview>
      |    |    |    | <UITextField>
      | <UITransitionView>
      |    | <UIView> ( UnityAdsEx.mm :: viewController.view )
      |    | <UIView> ( UADSViewController's view )
      |    |    | <WKWebView>
   ```
   
   The web view is moved from `USRVWebViewBackgroundView`, which remains hidden, to a new UITransitionView attached to the `SDL_uikitwindow`.

4. At some point, the video ad has its allowed orientations decided by Unity in some way, and the orientation is passed through the web view as a script message. This orientation may be `30`, which means all orientations allowed.

   ```
   #0  0x00000001041e7490 in -[UADSViewController setSupportedOrientations:] () <-------- 30
   #1  0x00000001041d4428 in +[UADSApiAdUnit WebViewExposed_setSupportedOrientations:callback:] ()
   #2  0x00000001a3c19b24 in __invoking___ ()
   #3  0x00000001a3c37610 in -[NSInvocation invoke] ()
   #4  0x000000010420b2cc in -[USRVInvocation nextInvocation] ()
   #5  0x000000010421ae38 in -[USRVWebViewMethodInvokeHandler handleInvocation:] ()
   #6  0x000000010421a878 in -[USRVWebViewMethodInvokeHandler handleData:invocationType:] ()
   #7  0x00000001042176f0 in -[USRVWebViewApp userContentController:didReceiveScriptMessage:] () <----- ["UADSApiAdUnit","setSupportedOrientations",[30],"848"]
   --  ------------------ -- ----------------------------------------------------------------
   #8  0x00000001b2bdb3e8 in ScriptMessageHandlerDelegate::didPostMessage(WebKit::WebPageProxy&, WebKit::FrameInfoData&&, API::ContentWorld&, WebCore::SerializedScriptValue&) ()
   #9  0x00000001b2f83d80 in WebKit::WebUserContentControllerProxy::didPostMessage(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::CompletionHandler<void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&)>&&) ()
   #10 0x00000001b32cb18c in WebKit::WebUserContentControllerProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) ()
   #11 0x00000001b2c81e10 in IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&) ()
   #12 0x00000001b2ece16c in WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) ()
   #13 0x00000001b2c672f0 in IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >) ()
   #14 0x00000001b2c66b08 in IPC::Connection::dispatchIncomingMessages() ()
   #15 0x00000001aeea97f0 in WTF::RunLoop::performWork() ()
   #16 0x00000001aeeaa58c in WTF::RunLoop::performWork(void*) ()
   #17 0x00000001a3cb3414 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
   #18 0x00000001a3cc41a0 in __CFRunLoopDoSource0 ()
   #19 0x00000001a3bfd694 in __CFRunLoopDoSources0 ()
   #20 0x00000001a3c0305c in __CFRunLoopRun ()
   #21 0x00000001a3c16bc8 in CFRunLoopRunSpecific ()
   #22 0x00000001bfd81374 in GSEventRunModal ()
   #23 0x00000001a658ab58 in -[UIApplication _run] ()
   #24 0x00000001a630c090 in UIApplicationMain ()
   #25 0x00000001048ba3d0 in SDL_UIKitRunApp at lime/project/lib/sdl/src/video/uikit/SDL_uikitappdelegate.m:70
   ```
   
5. Finally, when the ad is being closed, SDL receives the orientation changed event from iOS.
   
   ```
   #0  0x00000001047c7db0 in -[SDLUIKitDelegate application:didChangeStatusBarOrientation:] at lime/project/lib/sdl/src/video/uikit/SDL_uikitappdelegate.m:459
   #1  0x00000001a65246f8 in -[UIApplication setStatusBarOrientation:fromOrientation:windowScene:animationParameters:updateBlock:] ()
   #2  0x00000001a6170208 in __78-[UIWindow _rotateWindowToOrientation:updateStatusBar:duration:skipCallbacks:]_block_invoke ()
   #3  0x00000001a651a5cc in __58-[_UIWindowRotationAnimationController animateTransition:]_block_invoke_2 ()
   #4  0x00000001a63fbd48 in +[UIView _performBlockDelayingTriggeringResponderEvents:forScene:] ()
   #5  0x00000001a62ca9a4 in __58-[_UIWindowRotationAnimationController animateTransition:]_block_invoke ()
   #6  0x00000001a65d2e78 in -[_UIWindowRotationAnimationController animateTransition:] ()
   #7  0x00000001a66848b4 in -[UIWindow _rotateToBounds:withAnimator:transitionContext:] ()
   #8  0x00000001a650e2c8 in -[UIWindow _rotateWindowToOrientation:updateStatusBar:duration:skipCallbacks:] ()
   #9  0x00000001a613c3d0 in -[UIWindow _setRotatableClient:toOrientation:updateStatusBar:duration:force:isRotating:] ()
   #10 0x00000001a66e6ffc in -[UIWindow _setRotatableViewOrientation:updateStatusBar:duration:force:] ()
   #11 0x00000001a60c7388 in -[_UIFullscreenPresentationController _placeCounterRotationViewWithView:inWindow:fromOrientation:toOrientation:force:] ()
   #12 0x00000001a60c706c in -[_UIFullscreenPresentationController _adjustOrientationIfNecessaryInWindow:forViewController:preservingViewController:] () <----- orientation adjustment
   #13 0x00000001a63202a8 in -[UIPresentationController _dismissWithAnimationController:interactionController:target:didEndSelector:] ()
   #14 0x00000001a6348a38 in -[UIViewController _dismissViewControllerWithAnimationController:interactionController:completion:] ()
   #15 0x00000001a64ed2c0 in -[UIViewController _dismissViewControllerWithTransition:from:completion:] ()
   #16 0x00000001a642c5e0 in -[UIViewController dismissViewControllerWithTransition:completion:] ()
   #17 0x00000001a62d0e48 in -[UIViewController _performCoordinatedPresentOrDismiss:animated:] ()
   #18 0x00000001a632c8e0 in -[UIViewController dismissViewControllerAnimated:completion:] () <----- in response, unity ads dismisses "viewController.view" from UnityAdsEx.mm
   #19 0x00000001040e0198 in __38+[UADSApiAdUnit WebViewExposed_close:]_block_invoke () <----- ad is closed
   #20 0x0000000108870c70 in _dispatch_call_block_and_release ()
   #21 0x00000001088727c0 in _dispatch_client_callout ()
   #22 0x0000000108882c68 in _dispatch_main_queue_drain ()
   #23 0x00000001088827a4 in _dispatch_main_queue_callback_4CF ()
   #24 0x00000001a3c49800 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
   #25 0x00000001a3c03704 in __CFRunLoopRun ()
   #26 0x00000001a3c16bc8 in CFRunLoopRunSpecific ()
   #27 0x00000001bfd81374 in GSEventRunModal ()
   #28 0x00000001a658ab58 in -[UIApplication _run] ()
   #29 0x00000001a630c090 in UIApplicationMain ()
   #30 0x00000001047c64a0 in SDL_UIKitRunApp at lime/project/lib/sdl/src/video/uikit/SDL_uikitappdelegate.m:70
   ```

This call in the center looks like it's they key: `_adjustOrientationIfNecessaryInWindow:forViewController:preservingViewController:`.

```
[<_UIFullscreenPresentationController> _adjustOrientationIfNecessaryInWindow:<SDL_uikitwindow> forViewController:<UIViewController> (from UnityAdsEx.mm) preservingViewController:<UADSViewController>] (the container of the WKWebView)
```

I still haven't put my finger on exactly what's happening, but I think it has to do with how this extension does not present the view controller modally, but instead just adds it as a subview to the root view controller.
